[project]
name = "explore-py"
version = "0.0.0"
requires-python = ">=3.12.10"


[tool.uv.workspace]
members = [
    "apps/fastapi-auth",
]

[tool.uv.sources]

[dependency-groups]
dev = [
    "ruff",
]
